apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: my-aks-ingress.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /party-clippy
        backend:
          serviceName: party-clippy
          servicePort: 80
      - path: /webapp-ingress
        backend:
          serviceName: webapp1-clusterip-svc
          servicePort: 80